# Cross-Group Attention Test Config
# These datasets have multiple related time series that could benefit from cross-group attention
# (e.g., electricity prices across regions, traffic across locations)

- name: ercot
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1

- name: monash_australian_electricity
  hf_repo: autogluon/chronos_datasets
  offset: -48
  prediction_length: 48
  num_rolls: 1

- name: monash_traffic
  hf_repo: autogluon/chronos_datasets
  offset: -24
  prediction_length: 24
  num_rolls: 1
