- name: monash_tourism_monthly
  hf_repo: autogluon/chronos_datasets
  offset: -48
  prediction_length: 24
  num_rolls: 1

- name: nn5
  hf_repo: autogluon/chronos_datasets
  offset: -112
  prediction_length: 56
  num_rolls: 1
